apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge
  labels:
    app: challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge
  template:
    metadata:
      labels:
        app: challenge
    spec:
      containers:
        - name: challenge
          image: "leynerbueno/tech-challenge:latest"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: EMAIL_USER
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: EMAIL_PASS
          resources:
              requests:
                  cpu: "250m"
                  memory: "512Mi"
              limits:
                  cpu: "1"
                  memory: "1Gi"